name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Dotnet Tests
        run: dotnet test --configuration Release

      - name: Dotnet Publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionDotNet.Api.csproj --configuration Release -o artifacts
