name: Run at 15 minutes.

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  cron:
    name: Run at 15 minutes.
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello World"
